### PR TITLE
📕 Updates icon changed `EXTRA.md`

### PR DESCRIPTION
**Pull request by orisme12**
icon change was made for update `EXTRA.md`

### CODE REVIEW

**Review by santiagoRicops — APPROVED** [review]
aprovado👍

**Review by gerzon05 — APPROVED** [review]
Aprobado

**Review by orisme12 — COMMENTED** [review]
Se realizó el cambio del icono de update

**Comment by orisme12** [comment]
icon change was made for update EXTRA.md

**Review by castrogarciajs — APPROVED** [review]

**Pull request merged**
